name: ml_algo_examples
version: 0.0.1
author: Ilia Gyrdymov <ilgyrd@gmail.com>
description: Usage examples of ml_algo library
homepage: https://github.com/gyrdym/ml_algo_examples

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  ml_algo: ^14.2.0
  ml_dataframe: 0.1.1
  ml_linalg: ^12.17.1
  ml_preprocessing: ^5.1.0
  xrange: ^0.0.8

dev_dependencies:
  test: ^1.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
  pedantic: ^1.4.0
